
jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: |
          msbuild src/PCRE.NET.sln /v:m /t:Restore
        displayName: NuGet Restore
      - script: |
          msbuild src/PCRE.NET.sln /m /v:m /t:Rebuild /p:Configuration=Release
        displayName: Build
      - script: |
          msbuild src/PCRE.NET/PCRE.NET.csproj /v:m /t:Pack /p:Configuration=Release /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
        displayName: NuGet Pack
      - task: VSTest@2
        displayName: Test
        inputs:
          configuration: Release
          searchFolder: src/PCRE.NET.Tests/bin/Release
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          ArtifactName: NuGet
