
jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: MSBuild@1
        displayName: NuGet Restore
        inputs:
          configuration: Release
          maximumCpuCount: true
          msbuildArguments: /t:Restore /v:m
          solution: src/PCRE.NET.sln
      - task: MSBuild@1
        displayName: Build
        inputs:
          configuration: Release
          maximumCpuCount: true
          msbuildArguments: /t:Rebuild /v:m
          solution: src/PCRE.NET.sln
      - task: MSBuild@1
        displayName: NuGet Pack
        inputs:
          configuration: Release
          maximumCpuCount: true
          msbuildArguments: /t:Pack /v:m /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
          solution: src/PCRE.NET/PCRE.NET.csproj
      - task: VSTest@2
        displayName: Test
        inputs:
          configuration: Release
          searchFolder: src/PCRE.NET.Tests/bin/Release
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          ArtifactName: NuGet
