
jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - bash: |
          mkdir src/cmake-x86
          mkdir src/cmake-x64
          sudo apt-get install gcc-multilib g++-multilib
        displayName: Init
      - task: CMake@1
        displayName: CMake x86
        inputs:
          workingDirectory: src/cmake-x86
          cmakeArgs: .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
      - task: CMake@1
        displayName: CMake x64
        inputs:
          workingDirectory: src/cmake-x64
          cmakeArgs: .. -DCMAKE_BUILD_TYPE=Release
      - bash: |
          cd $(Build.SourcesDirectory)/src/cmake-x86
          make
        displayName: Build x86
      - bash: |
          cd $(Build.SourcesDirectory)/src/cmake-x64
          make
        displayName: Build x64
      - task: PublishPipelineArtifact@0
        displayName: Publish x86 Artifact
        inputs:
          artifactName: PCRE.NET.Native.x86.so
          targetPath: src/cmake-x86/PCRE.NET.Native.so
      - task: PublishPipelineArtifact@0
        displayName: Publish x64 Artifact
        inputs:
          artifactName: PCRE.NET.Native.x64.so
          targetPath: src/cmake-x64/PCRE.NET.Native.so

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: MSBuild@1
        displayName: NuGet Restore
        inputs:
          configuration: Release
          maximumCpuCount: true
          msbuildArguments: /t:Restore /v:m
          solution: src/PCRE.NET.sln
      - task: MSBuild@1
        displayName: Build Native x86
        inputs:
          configuration: Release
          platform: Win32
          maximumCpuCount: true
          msbuildArguments: /v:m
          solution: src/PCRE.NET.Native/PCRE.NET.Native.vcxproj
      - task: MSBuild@1
        displayName: Build Native x64
        inputs:
          configuration: Release
          platform: x64
          maximumCpuCount: true
          msbuildArguments: /v:m
          solution: src/PCRE.NET.Native/PCRE.NET.Native.vcxproj
      - task: MSBuild@1
        displayName: Build
        inputs:
          configuration: Release
          maximumCpuCount: true
          msbuildArguments: /v:m
          solution: src/PCRE.NET.sln
      - task: MSBuild@1
        displayName: NuGet Pack
        inputs:
          configuration: Release
          maximumCpuCount: true
          msbuildArguments: /t:Pack /v:m /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
          solution: src/PCRE.NET/PCRE.NET.csproj
      - task: VSTest@2
        displayName: Test x86
        inputs:
          configuration: Release
          platform: x86
          searchFolder: src/PCRE.NET.Tests/bin/Release
      - task: VSTest@2
        displayName: Test x64
        inputs:
          configuration: Release
          platform: x64
          searchFolder: src/PCRE.NET.Tests/bin/Release
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          ArtifactName: NuGet
